### PR TITLE
fix: Fixes #22 and #27 by adding custom signin page and show password with shadcn

### LINKED ISSUE #22: Signin Button looks like link but there should be different background color and text decoration of button have to be removed for better UX
Here is the issue , what it looks like when visiting auth/signin route of 100xdev webpage.
image

### PR DESCRIPTION
**Pull request by shreyas0924**
Fixes #22 and #27 
1. Added custom login page by adding /sigin route and add the same in next-auth pages (auth.ts file)
2. Show and hide password

https://github.com/code100x/cms/assets/72003665/be0eda2f-69bf-41eb-8ae7-e829fee2bed3

### CODE REVIEW

File: src/app/signin/page.tsx [hunk 1]
```diff
@@ -0,0 +1,112 @@
...
+  const password = useRef('');
+  const handleSubmit = async (e: React.FormEvent<HTMLButtonElement>) => {
+    e.preventDefault();
+    const res = await signIn('credentials', {
+      email: email.current,
+      password: password.current,
+      redirect: false,
+    });
+
+    if (!res?.error) {
```
Comment (siinghd) [inline src/app/signin/page.tsx:27]: I think it would be also better to add an alert or something to notify the user about the error.

**Review by siinghd — CHANGES_REQUESTED** [review]
Add an alert to notify the user about the error

File: src/app/signin/page.tsx (hunk 1 above)
Comment (shreyas0924) [reply src/app/signin/page.tsx:27]: I'll do it now

Comment (shreyas0924) [reply src/app/signin/page.tsx:29]: Added Sonner toast..

image

File: src/app/signin/page.tsx [hunk 2]
```diff
@@ -26,6 +28,13 @@ const Signin = () => {
 
     if (!res?.error) {
       router.push('/');
+    } else {
+      toast('Error Signing in', {
```
Comment (siinghd) [inline src/app/signin/page.tsx:32]: Can't this error be more specific? res?.error probably. Might be good to display the returned error insted of static message.

**Review by siinghd — CHANGES_REQUESTED** [review]
Change static message to dynamic

File: src/app/signin/page.tsx (hunk 2 above)
Comment (hkirat) [reply src/app/signin/page.tsx:32]: Yeah should address this in a follow up, merging for now as a v1
