### PR TITLE
bug: Security vulnerabilities in external Login API endpoint

### LINKED ISSUE #1416: bug: Security vulnerabilities in external Login API endpoint
**Describe the bug**
The current authentication API endpoint (/api/admin/services/externalLogin/route.ts) has several security vulnerabilities that need to be addressed:

1. Potential timing attacks due to different response times for existing vs non-existing users
2. Excessive data exposure in the API response
3. Insufficient input validation
4. Inconsistent error messages that could lead to user enumeration
5. Inadequate error handling and logging

**To Reproduce**
1. Send a POST request to the /api/admin/services/externalLogin endpoint with valid Auth-Key but invalid user credentials
2. Observe that the response times may differ for existing vs non-existing users
3. Send a POST request with valid credentials
4. Observe that sensitive user data is returned in the response

**Expected behavior**
1. The API should have consistent response times regardless of whether a user exists or not
2. Input should be properly validated before processing
3. Only necessary user data should be returned in the response
4. Error messages should be generic to prevent user enumeration
5. Proper error handling and logging should be implemented

**Additional context**
This issue affects the security of our authentication system and should be addressed promptly to prevent potential exploits.

### PR DESCRIPTION
**Pull request by kushwahramkumar2003**
PR Fixes:
- Mitigate potential timing attacks
- Reduce excessive data exposure
- Implement robust input validation using Zod
- Standardize error messages to prevent user enumeration
- Improve error handling and logging

Resolves #1416 

Description:
This pull request addresses the security vulnerabilities identified in our external Login API endpoint. The following improvements have been implemented:

1. Timing attack mitigation: Implemented a constant-time comparison for non-existent users to prevent timing-based enumeration attacks.

2. Data exposure reduction: Limited the user and course data returned in the API response to only necessary fields, preventing exposure of sensitive information.

3. Input validation: Integrated Zod for robust input validation, ensuring that email and password inputs are properly validated before processing.

4. Error message standardization: Implemented consistent error messages for invalid credentials, regardless of whether the user exists or not, to prevent user enumeration.

5. Error handling and logging: Improved error handling with more specific logging while keeping client-facing messages generic to enhance security and maintainability.

These changes significantly enhance the security of our authentication system while maintaining compatibility with the existing job-board application.

Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

File: src/app/api/admin/services/externalLogin/route.ts [hunk 1]
```diff
@@ -1,7 +1,13 @@
+import { z } from 'zod';
 import db from '@/db';
 import { NextRequest, NextResponse } from 'next/server';
 import bcrypt from 'bcrypt';
 
+const loginSchema = z.object({
+  email: z.string().email(),
```
Comment (devsargam) [inline src/app/api/admin/services/externalLogin/route.ts:7]: This is not necessarily just a email it can be any string or number

File: src/app/api/admin/services/externalLogin/route.ts [hunk 2]
```diff
@@ -11,49 +17,69 @@ export async function POST(req: NextRequest) {
...
         email: true,
         name: true,
         password: true,
       },
     });
-    if (!user) {
-      return NextResponse.json({ message: 'User not found' }, { status: 404 });
+
+    // Perform a dummy bcrypt compare if user doesn't exist to prevent timing attacks
+    if (!user || !user.password) {
```
Comment (devsargam) [inline src/app/api/admin/services/externalLogin/route.ts:42]: Can do make another pr with just this change and nothing else.

**Review by devsargam — CHANGES_REQUESTED** [review]

File: src/app/api/admin/services/externalLogin/route.ts (hunk 1 above)
Comment (kushwahramkumar2003) [reply src/app/api/admin/services/externalLogin/route.ts:7]: done

File: src/app/api/admin/services/externalLogin/route.ts [hunk 3]
```diff
@@ -11,49 +17,69 @@ export async function POST(req: NextRequest) {
...
         data: {
-          user,
+          user: {
+            id: user.id,
+            email: user.email,
+            name: user.name,
+          },
           courses,
         },
       });
```
Comment (kushwahramkumar2003) [inline src/app/api/admin/services/externalLogin/route.ts:73]: exclude user password, can we need courses in response

File: src/app/api/admin/services/externalLogin/route.ts (hunk 2 above)
Comment (kushwahramkumar2003) [reply src/app/api/admin/services/externalLogin/route.ts:42]: Done

**Comment by kushwahramkumar2003** [comment]
@devsargam @hkirat please review again

**Review by devsargam — APPROVED** [review]

**Comment by devsargam** [comment]
LGTM! Will merge after the current version is properly deployed

**Comment by kushwahramkumar2003** [comment]
waiting for merge :)
